In [18]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns

ignorewarnings = True

# Collecting Data Pertumbuhan Tanaman

In [19]:
df_jumlah_daun = pd.read_excel('../dataTumbuhanPakcoy/jumlahDaun.xlsx')
df_jumlah_daun.head()

   Tanaman Pakcoy  0  3  6  9  12  15  18  21  24  27  30
0               1  4  5  5  8  10  10  14  16  18  20  20
1               2  4  5  5  7   9  10  14  15  17  19  20
2               3  4  6  5  7   9  11  13  15  18  16  18
3               4  4  5  5  6   8   9  11  15  17  20  22
4               5  4  5  5  6   8   8  11  12  13  19  19

In [20]:
df_lebar_daun = pd.read_excel('../dataTumbuhanPakcoy/lebarDaun.xlsx')
df_lebar_daun.head()

   Tanaman Pakcoy     0    3    6    9   12   15   18   21   24   27   30
0               1  1.08  1.8  3.2  5.0  6.2  7.1  7.3  7.6  8.5  8.8  9.2
1               2  1.08  1.8  2.8  4.2  5.2  5.6  6.1  6.6  7.7  7.4  7.0
2               3  1.26  2.1  2.5  4.6  6.2  6.6  7.2  7.4  9.0  9.0  8.9
3               4  1.30  1.5  2.5  3.8  5.2  5.6  5.7  6.2  7.9  8.5  9.0
4               5  1.00  1.0  2.4  3.8  4.7  5.0  5.3  6.1  8.2  7.9  8.8

In [21]:
df_panjang_daun = pd.read_excel('../dataTumbuhanPakcoy/panjangDaun.xlsx')
df_panjang_daun.head()

,Tanaman Pakcoy,0,3,6,9,12,15,18,21,24,27,30
0,1,2.38,3.3,5.3,8.2,10.0,10.5,11.8,11.5,11.2,12.4,13.5
1,2,2.08,2.8,4.4,7.0,8.1,9.3,10.1,11.7,13.2,12.9,12.5
2,3,2.10,3.5,4.5,8.0,9.5,10.2,10.9,11.5,12.0,13.5,15.0
3,4,1.50,2.5,4.1,7.2,8.8,9.3,9.9,10.2,10.5,12.5,14.4
4,5,1.30,1.5,4.0,6.5,8.0,8.4,9.1,9.9,10.8,12.4,13.9

In [22]:
df_tinggi_tanaman = pd.read_excel('../dataTumbuhanPakcoy/tinggiTanaman.xlsx')
df_tinggi_tanaman.head()

,Tanaman Pakcoy,0,3,6,9,12,15,18,21,24,27,30
0,1,3.36,6.1,9.5,12.0,16.5,17.8,18.6,18.9,19.2,21.0,22.8
1,2,3.58,6.5,7.4,12.5,24.0,16.0,17.2,17.9,18.7,19.6,20.5
2,3,4.12,7.5,8.2,12.2,15.6,17.5,18.8,19.4,20.0,20.0,20.0
3,4,3.26,5.2,8.2,12.1,14.5,16.4,17.0,16.8,17.5,19.1,20.6
4,5,2.02,4.0,7.4,11.6,13.2,15.0,16.7,16.8,18.4,19.2,19.8

### Ubah format data tanaman menjadi perhari untuk baris

In [23]:
df_jumlah_daun_long = df_jumlah_daun.melt(
    id_vars=["Tanaman Pakcoy"],
    var_name="hari_ke",
    value_name="jumlah_daun"
)
df_jumlah_daun_long.head()

   Tanaman Pakcoy hari_ke  jumlah_daun
0               1       0            4
1               2       0            4
2               3       0            4
3               4       0            4
4               5       0            4

In [24]:
df_lebar_daun_long = df_lebar_daun.melt(
    id_vars=["Tanaman Pakcoy"],
    var_name="hari_ke",
    value_name="lebar_daun"
)
df_lebar_daun_long.head()

   Tanaman Pakcoy hari_ke  lebar_daun
0               1       0        1.08
1               2       0        1.08
2               3       0        1.26
3               4       0        1.30
4               5       0        1.00

In [25]:
df_panjang_daun_long = df_panjang_daun.melt(
    id_vars=["Tanaman Pakcoy"],
    var_name="hari_ke",
    value_name="panjang_daun"
)
df_panjang_daun_long.head()

   Tanaman Pakcoy hari_ke  panjang_daun
0               1       0          2.38
1               2       0          2.08
2               3       0          2.10
3               4       0          1.50
4               5       0          1.30

In [26]:
df_tinggi_tanaman_long = df_tinggi_tanaman.melt(
    id_vars=["Tanaman Pakcoy"],
    var_name="hari_ke",
    value_name="tinggi_tanaman"
)
df_tinggi_tanaman_long.head()

   Tanaman Pakcoy hari_ke  tinggi_tanaman
0               1       0            3.36
1               2       0            3.58
2               3       0            4.12
3               4       0            3.26
4               5       0            2.02

In [27]:
for df in [df_jumlah_daun_long, df_tinggi_tanaman_long, df_panjang_daun_long, df_lebar_daun_long]:
    df["hari_ke"] = df["hari_ke"].astype(int)
    df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Tanaman Pakcoy  605 non-null    int64
 1   hari_ke         605 non-null    int32
 2   jumlah_daun     605 non-null    int64
dtypes: int32(1), int64(2)
memory usage: 11.9 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Tanaman Pakcoy  605 non-null    int64
 1   hari_ke         605 non-null    int32
 2   tinggi_tanaman  605 non-null    float64
dtypes: float64(1), int32(1), int64(1)
memory usage: 11.9 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Tanaman Pakcoy  605 non-null    int64
 1   hari_ke         605 non-null    int32
 2   panjang_daun    605 non-null    float64
dtypes: float64(1), int32(1), int64(1)
memory usage: 11.9 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Tanaman Pakcoy  605 non-null    int64
 1   hari_ke         605 non-null    int32
 2   lebar_daun      605 non-null    float64
dtypes: float64(1), int32(1), int64(1)
memory usage: 11.9 KB

In [28]:
df_gabungan = df_jumlah_daun_long.merge(df_tinggi_tanaman_long, on=["Tanaman Pakcoy", "hari_ke"], how="outer")
df_gabungan = df_gabungan.merge(df_panjang_daun_long, on=["Tanaman Pakcoy", "hari_ke"], how="outer")
df_gabungan = df_gabungan.merge(df_lebar_daun_long, on=["Tanaman Pakcoy", "hari_ke"], how="outer")

In [29]:
df_gabungan.head()

,Tanaman Pakcoy,hari_ke,jumlah_daun,tinggi_tanaman,panjang_daun,lebar_daun
0,1,0,4,3.36,2.38,1.08
1,2,0,4,3.58,2.08,1.08
2,3,0,4,4.12,2.10,1.26
3,4,0,4,3.26,1.50,1.30
4,5,0,4,2.02,1.30,1.00

In [30]:
df_gabungan.to_excel("gabungan_data.xlsx", index=False)

# Collecting Data Sensor

In [31]:
base_path = "../Excel penelitian"
data_list = []

In [32]:
for folder in os.listdir(base_path):
    folder_path = os.path.join(base_path, folder)
    if os.path.isdir(folder_path):
        tanggal = folder

        try:
            ph = pd.read_excel(os.path.join(folder_path, "pH.xlsx"))
            ppm = pd.read_excel(os.path.join(folder_path, "PPM.xlsx"))
            suhu_air = pd.read_excel(os.path.join(folder_path, "Suhu air.xlsx"))
            suhu_dht = pd.read_excel(os.path.join(folder_path, "Suhu dht.xlsx"))
            hum_dht = pd.read_excel(os.path.join(folder_path, "Humadity dht.xlsx"))

            avg_ph = ph.mean(numeric_only=True).mean()
            avg_ppm = ppm.mean(numeric_only=True).mean()
            avg_suhu_air = suhu_air.mean(numeric_only=True).mean()
            avg_suhu_dht = suhu_dht.mean(numeric_only=True).mean()
            avg_hum_dht = hum_dht.mean(numeric_only=True).mean()

            data_list.append({
                "tanggal": tanggal,
                "ph": avg_ph,
                "ppm": avg_ppm,
                "suhu_air": avg_suhu_air,
                "suhu_dht": avg_suhu_dht,
                "humidity_dht": avg_hum_dht
            })
        except Exception as e:
            print(f"Gagal baca folder {folder}: {e}")

df_sensor = pd.DataFrame(data_list)

In [33]:
df_sensor["tanggal"] = pd.to_datetime(df_sensor["tanggal"], format="%d-%m-%Y")

In [34]:
df_sensor = df_sensor.sort_values("tanggal")

In [35]:
df_sensor.head()

      tanggal        ph         ppm   suhu_air   suhu_dht  humidity_dht
17 2025-07-29  6.066393  888.677043  28.264710  31.636839     70.785572
18 2025-07-30  6.074200  899.197696  29.782634  28.664605     81.157431
19 2025-07-31  6.078210  891.725696  29.292634  28.225913     83.321099
0  2025-08-01       NaN  907.181192  29.152341  30.018621     78.052429
1  2025-08-02  6.068300  909.949696  27.625678  29.069981     78.720740

In [36]:
df_sensor.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20 entries, 17 to 16
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   tanggal       20 non-null     datetime64[ns]
 1   ph            19 non-null     float64
 2   ppm           20 non-null     float64
 3   suhu_air      20 non-null     float64
 4   suhu_dht      20 non-null     float64
 5   humidity_dht  20 non-null     float64
dtypes: datetime64[ns](1), float64(5)
memory usage: 1.1 KB

In [37]:
df_sensor["tanggal"].sort_values().unique()

array(['2025-07-29T00:00:00.000000000', '2025-07-30T00:00:00.000000000',
       '2025-07-31T00:00:00.000000000', '2025-08-01T00:00:00.000000000',
       '2025-08-02T00:00:00.000000000', '2025-08-03T00:00:00.000000000',
       '2025-08-05T00:00:00.000000000', '2025-08-06T00:00:00.000000000',
       '2025-08-07T00:00:00.000000000', '2025-08-08T00:00:00.000000000',
       '2025-08-09T00:00:00.000000000', '2025-08-10T00:00:00.000000000',
       '2025-08-11T00:00:00.000000000', '2025-08-12T00:00:00.000000000',
       '2025-08-13T00:00:00.000000000', '2025-08-16T00:00:00.000000000',
       '2025-08-19T00:00:00.000000000', '2025-08-22T00:00:00.000000000',
       '2025-08-25T00:00:00.000000000', '2025-08-28T00:00:00.000000000'],
      dtype='datetime64[ns]')

In [38]:
print("Tanggal paling awal:", df_sensor["tanggal"].min())
print("Tanggal paling akhir:", df_sensor["tanggal"].max())

Tanggal paling awal: 2025-07-29 00:00:00
Tanggal paling akhir: 2025-08-28 00:00:00

In [39]:
duplicates = df_sensor[df_sensor.duplicated(subset="tanggal", keep=False)]
print(duplicates)

Empty DataFrame
Columns: [tanggal, ph, ppm, suhu_air, suhu_dht, humidity_dht]
Index: []

In [40]:
df_sensor = df_sensor.sort_values("tanggal")
df_sensor["diff_days"] = df_sensor["tanggal"].diff().dt.days
print(df_sensor[["tanggal", "diff_days"]])

      tanggal  diff_days
17 2025-07-29        NaN
18 2025-07-30        1.0
19 2025-07-31        1.0
0  2025-08-01        1.0
1  2025-08-02        1.0
2  2025-08-03        1.0
3  2025-08-05        2.0
4  2025-08-06        1.0
5  2025-08-07        1.0
6  2025-08-08        1.0
7  2025-08-09        1.0
8  2025-08-10        1.0
9  2025-08-11        1.0
10 2025-08-12        1.0
11 2025-08-13        1.0
12 2025-08-16        3.0
13 2025-08-19        3.0
14 2025-08-22        3.0
15 2025-08-25        3.0
16 2025-08-28        3.0

In [41]:
print(df_sensor.info())
print(df_sensor.isna().sum())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20 entries, 17 to 16
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   tanggal       20 non-null     datetime64[ns]
 1   ph            19 non-null     float64
 2   ppm           20 non-null     float64
 3   suhu_air      20 non-null     float64
 4   suhu_dht      20 non-null     float64
 5   humidity_dht  20 non-null     float64
 6   diff_days     19 non-null     float64
dtypes: datetime64[ns](1), float64(6)
memory usage: 1.2 KB
None
tanggal         0
ph              1
ppm             0
suhu_air        0
suhu_dht        0
humidity_dht    0
diff_days       1
dtype: int64

#### Wrangling data

In [42]:
df_sensor_clean = df_sensor.drop_duplicates(subset="tanggal").sort_values("tanggal")

In [43]:
df_sensor_clean["ph"] = df_sensor_clean["ph"].interpolate(method="linear")

In [44]:
tanggal_penuh = pd.date_range(df_sensor_clean["tanggal"].min(), df_sensor_clean["tanggal"].max())

In [45]:
df_sensor_clean = df_sensor_clean.set_index("tanggal").reindex(tanggal_penuh).rename_axis("tanggal").reset_index()

In [46]:
df_sensor_clean[df_sensor_clean.select_dtypes(include=['float64']).columns] = (
    df_sensor_clean.select_dtypes(include=['float64']).interpolate(method='linear')
)

In [47]:
df_sensor_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   tanggal       31 non-null     datetime64[ns]
 1   ph            31 non-null     float64
 2   ppm           31 non-null     float64
 3   suhu_air      31 non-null     float64
 4   suhu_dht      31 non-null     float64
 5   humidity_dht  31 non-null     float64
 6   diff_days     30 non-null     float64
dtypes: datetime64[ns](1), float64(6)
memory usage: 1.8 KB

In [48]:
df_sensor_clean['tanggal'] = pd.to_datetime(df_sensor_clean['tanggal'], errors='coerce')

In [49]:
df_sensor_clean['diff_days'] = (df_sensor_clean['tanggal'] - df_sensor_clean['tanggal'].min()).dt.days

In [50]:
df_sensor_clean.isna().sum()

tanggal         0
ph              0
ppm             0
suhu_air        0
suhu_dht        0
humidity_dht    0
diff_days       0
dtype: int64

In [51]:
df_sensor_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   tanggal       31 non-null     datetime64[ns]
 1   ph            31 non-null     float64
 2   ppm           31 non-null     float64
 3   suhu_air      31 non-null     float64
 4   suhu_dht      31 non-null     float64
 5   humidity_dht  31 non-null     float64
 6   diff_days     31 non-null     int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 1.8 KB

In [52]:
df_sensor_clean.head()

,tanggal,ph,ppm,suhu_air,suhu_dht,humidity_dht,diff_days
0,2025-07-29,6.066393,888.677043,28.264710,31.636839,70.785572,0
1,2025-07-30,6.074200,899.197696,29.782634,28.664605,81.157431,1
2,2025-07-31,6.078210,891.725696,29.292634,28.225913,83.321099,2
3,2025-08-01,6.073255,907.181192,29.152341,30.018621,78.052429,3
4,2025-08-02,6.068300,909.949696,27.625678,29.069981,78.720740,4

In [53]:
df_sensor_clean["diff_days"].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
      dtype=int64)

In [54]:
df_sensor_clean['hari_ke'] = range(len(df_sensor_clean))

In [55]:
df_sensor_clean.head()

,tanggal,ph,ppm,suhu_air,suhu_dht,humidity_dht,diff_days,hari_ke
0,2025-07-29,6.066393,888.677043,28.264710,31.636839,70.785572,0,0
1,2025-07-30,6.074200,899.197696,29.782634,28.664605,81.157431,1,1
2,2025-07-31,6.078210,891.725696,29.292634,28.225913,83.321099,2,2
3,2025-08-01,6.073255,907.181192,29.152341,30.018621,78.052429,3,3
4,2025-08-02,6.068300,909.949696,27.625678,29.069981,78.720740,4,4

In [56]:
df_sensor_clean["hari_ke"].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
      dtype=int64)

In [57]:
df_sensor_clean = df_sensor_clean.drop(columns=['diff_days'])

# Merge dua dataset

In [58]:
df_final = pd.merge(df_gabungan, df_sensor_clean, on='hari_ke', how='left')

In [59]:
rename_map = {
    "Tanaman Pakcoy": "plant",
    "hari_ke": "day",
    "jumlah_daun": "leaf_count",
    "lebar_daun": "leaf_width",
    "panjang_daun": "leaf_length",
    "tinggi_tanaman": "plant_height",
    "tanggal": "date",
    "suhu_air": "water_temp",
    "suhu_dht": "air_temp",
    "humidity_dht": "humidity"
}

In [60]:
df_final.rename(columns=rename_map, inplace=True)

In [61]:
if "plant" in df_final.columns:
    df_final["plant"] = df_final["plant"].replace({"Tanaman Pakcoy": "Pak Choi"})

In [62]:
df_final.head()

,plant,day,leaf_count,plant_height,leaf_length,leaf_width,date,ph,ppm,water_temp,air_temp,humidity
0,1,0,4,3.36,2.38,1.08,2025-07-29,6.066393,888.677043,28.26471,31.636839,70.785572
1,2,0,4,3.58,2.08,1.08,2025-07-29,6.066393,888.677043,28.26471,31.636839,70.785572
2,3,0,4,4.12,2.10,1.26,2025-07-29,6.066393,888.677043,28.26471,31.636839,70.785572
3,4,0,4,3.26,1.50,1.30,2025-07-29,6.066393,888.677043,28.26471,31.636839,70.785572
4,5,0,4,2.02,1.30,1.00,2025-07-29,6.066393,888.677043,28.26471,31.636839,70.785572

In [63]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 605 entries, 0 to 604
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   plant         605 non-null    int64
 1   day           605 non-null    int32
 2   leaf_count    605 non-null    int64
 3   plant_height  605 non-null    float64
 4   leaf_length   605 non-null    float64
 5   leaf_width    605 non-null    float64
 6   date          605 non-null    datetime64[ns]
 7   ph            605 non-null    float64
 8   ppm           605 non-null    float64
 9   water_temp    605 non-null    float64
 10  air_temp      605 non-null    float64
 11  humidity      605 non-null    float64
dtypes: datetime64[ns](1), float64(8), int32(1), int64(2)
memory usage: 59.1 KB

In [64]:
df_final['leaf_width'] = pd.to_numeric(df_final['leaf_width'], errors='coerce')

In [65]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 605 entries, 0 to 604
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   plant         605 non-null    int64
 1   day           605 non-null    int32
 2   leaf_count    605 non-null    int64
 3   plant_height  605 non-null    float64
 4   leaf_length   605 non-null    float64
 5   leaf_width    605 non-null    float64
 6   date          605 non-null    datetime64[ns]
 7   ph            605 non-null    float64
 8   ppm           605 non-null    float64
 9   water_temp    605 non-null    float64
 10  air_temp      605 non-null    float64
 11  humidity      605 non-null    float64
dtypes: datetime64[ns](1), float64(8), int32(1), int64(2)
memory usage: 59.1 KB

In [66]:
df_final.to_excel("data_final_pakcoy.xlsx", index=False)